# Generated by Django 4.2.3 on 2023-07-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_slug_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='conclusion',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='content5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title3',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title4',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='title5',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
