# Generated by Django 4.2.3 on 2023-07-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_conclusion_post_content2_post_content3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content1',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title5',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content5',
            new_name='introcontent',
        ),
        migrations.AddField(
            model_name='post',
            name='title1',
            field=models.CharField(default='', max_length=255),
        ),
    ]
