# Generated by Django 4.2.3 on 2023-07-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_content_post_content1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content5',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='title5',
            field=models.CharField(default='', max_length=255),
        ),
    ]
