# Generated by Django 4.2.3 on 2023-07-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogcomment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title5',
        ),
    ]
