# Generated by Django 4.2.3 on 2023-07-30 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_post_content1_remove_post_content2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content5',
            new_name='content',
        ),
    ]
