# Generated by Django 4.2.3 on 2023-07-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_content5_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='conclusion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='introcontent',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
