# Generated by Django 4.2.3 on 2023-07-31 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_remove_post_conclusion_remove_post_introcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(default=0, to=settings.AUTH_USER_MODEL),
        ),
    ]
